#!/bin/sh

echo "Please input keystore name:"
read keystore

echo "Please input alias name:"
read aliasName

echo "Please input validity (days):"
read validity

keytool -genkey -v -keystore $keystore -alias $aliasName -keyalg RSA -keysize 2048 -validity $validity

