#!/bin/sh

# keystore type
echo "Is it a debug keystore? (y/n)"
read isDebug
if [ -z "$isDebug" ]
then
    isDebug="no"
fi

case $isDebug in
y|Y|yes|Yes|YES )
    echo "Choose yes"
    isDebug=true
    ;;
n|N|no|No|NO )
    echo "Choose no"
    isDebug=false
    ;;
* )
    echo "No input, default no"
    isDebug=false
    ;;
esac

# keystore name
echo "Please input keystore name:"
read keystore

if [ -z "$keystore" ]
then
    echo "keystore not input"
    exit -1
fi

# alias name
echo "Please input alias name:"
read aliasName

if [ -z "$aliasName" ]
then
    echo "alias name not input"
    exit -1
fi

# validity
echo "Please input validity (days):"
read validity

if [ -z "$validity" ]
then
    echo "validity not input"
    exit -1
fi

# execute cmd
if $isDebug
then
    keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000
else
    keytool -genkey -v -keystore $keystore -alias $aliasName -keyalg RSA -keysize 2048 -validity $validity
fi


