#!/bin/sh

getCanonicalPath() {
    canonicalPath="`cd "$1";pwd`"
}

echo "Type first dir and press enter:"
read firstDir
getCanonicalPath $firstDir
firstDir=$canonicalPath

echo "Type second dir and press enter:"
read secondDir
getCanonicalPath $secondDir
secondDir=$canonicalPath

vim -c "DirDiff $firstDir $secondDir"

