#!/bin/sh

set -e

echo "Please input your project name:"
read name
if [ -z $name ]
then
    echo "name should not be empty"
    exit -1
fi

mkdir $name

cd $name

echo "please input board ID: (e.g. uno, mhetesp32devkit)"
read board
if [ -z $board ]
then
    echo "board should not be empty"
    exit -1
fi

echo "please input project-option: (e.g. framework=espidf,framework=arduino,lib_deps=ArduinoJSON. Or leave it empty to use default)"
read option

cmd="pio project init --board $board"
if [ -n $option ]
then
    IFS=','
    read -ra splitarray <<< "$option"
    IFS=' '

    all_options=""
    for i in "${splitarray[@]}"; do
        all_options="$all_options --project-option $i"
    done

    cmd="$cmd $all_options"
fi

echo $cmd
$cmd

# .gitignore
echo "generate .gitignore"
echo ".pio\n.pioenvs\n.piolibdeps\n.vscode/\n.ccls\n.clang_complete\n.gcc-flags.json\n.ccls-cache/\nbuild/\ntags\n" > .gitignore

echo "\nSuccess"
