#!/usr/bin/env python3

import argparse
import os
import sys
from typing import List, Tuple

RED = '\033[0;31m'
GREEN = '\033[0;32m'
YELLOW = '\033[0;33m'
NC = '\033[0m'


def eprint(msg: str) -> None:
    print(msg, file=sys.stderr)


def resolve_git_dir(cwd: str) -> Tuple[str, str]:
    git_path = os.path.join(cwd, '.git')
    if os.path.isdir(git_path):
        return git_path, git_path
    if os.path.isfile(git_path):
        try:
            with open(git_path, 'r', encoding='utf-8') as f:
                first = f.readline().strip()
        except Exception as exc:
            raise RuntimeError(f"Failed to read {git_path}: {exc}")
        if not first.startswith('gitdir:'):
            raise RuntimeError(f"Unexpected .git file format: {git_path}")
        gitdir = first.split(':', 1)[1].strip()
        if not os.path.isabs(gitdir):
            gitdir = os.path.normpath(os.path.join(cwd, gitdir))
        return git_path, gitdir
    raise RuntimeError(f".git not found in current directory: {cwd}")


def build_hook_content(terms: List[str]) -> str:
    terms_repr = repr(terms)
    template = """#!/usr/bin/env python3
# Auto-generated by install_sensitive_commit_msg_hook.py
# This commit-msg hook blocks commit when staged changes contain sensitive terms.

import os
import subprocess
import sys
from typing import Dict, List, Set

RED = '\\033[0;31m'
GREEN = '\\033[0;32m'
YELLOW = '\\033[0;33m'
NC = '\\033[0m'

SENSITIVE_TERMS = __TERMS__


def run_git(args: List[str]) -> subprocess.CompletedProcess:
    return subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)


def get_repo_root() -> str:
    result = run_git(['git', 'rev-parse', '--show-toplevel'])
    if result.returncode != 0:
        return os.getcwd()
    return result.stdout.strip()


def scan_staged_diff(terms: List[str]) -> Dict[str, Set[str]]:
    result = run_git(['git', 'diff', '--cached', '-U0'])
    if result.returncode != 0:
        return {}

    current_file = ''
    hits: Dict[str, Set[str]] = {}
    lower_terms = [t.lower() for t in terms]

    for line in result.stdout.splitlines():
        if line.startswith('diff --git '):
            # Format: diff --git a/xxx b/xxx
            parts = line.split(' ')
            if len(parts) >= 4:
                current_file = parts[3].replace('b/', '', 1)
            continue
        if line.startswith('+++ ') or line.startswith('--- ') or line.startswith('@@'):
            continue
        if not line.startswith('+'):
            continue
        if line.startswith('+++'):
            continue

        content = line[1:]
        content_lower = content.lower()
        for idx, term in enumerate(lower_terms):
            if term and term in content_lower:
                original_term = terms[idx]
                hits.setdefault(original_term, set()).add(current_file or '(unknown)')
    return hits


def main() -> int:
    if not SENSITIVE_TERMS:
        return 0

    os.chdir(get_repo_root())
    hits = scan_staged_diff(SENSITIVE_TERMS)
    if not hits:
        return 0

    sys.stderr.write(f"{RED}Blocked commit: sensitive terms found in staged changes.{NC}\\n")
    for term, files in hits.items():
        files_list = ', '.join(sorted(files))
        sys.stderr.write(f"  - {term} -> {files_list}\\n")
    sys.stderr.write(f"{YELLOW}If this is intended, update the hook list.{NC}\\n")
    return 1


if __name__ == '__main__':
    sys.exit(main())
"""
    return template.replace("__TERMS__", terms_repr)


def main() -> int:
    parser = argparse.ArgumentParser(
        description='Install a commit-msg hook to block commits containing sensitive terms in staged changes.'
    )
    parser.add_argument('terms', nargs='*', help='Sensitive terms to block (space separated).')
    args = parser.parse_args()
    if not args.terms:
        eprint(f"{RED}Error: please provide at least one sensitive term.{NC}")
        eprint(f"{YELLOW}Example: git-sensitive-hook aaa bbb ccc{NC}")
        return 2

    cwd = os.getcwd()
    try:
        _, git_dir = resolve_git_dir(cwd)
    except RuntimeError as exc:
        eprint(f"{RED}Error: {exc}{NC}")
        return 1

    hooks_dir = os.path.join(git_dir, 'hooks')
    os.makedirs(hooks_dir, exist_ok=True)
    hook_path = os.path.join(hooks_dir, 'commit-msg')

    content = build_hook_content(args.terms)
    if os.path.exists(hook_path):
        try:
            with open(hook_path, 'r', encoding='utf-8') as f:
                existing = f.read()
            if existing == content:
                print(f"{GREEN}commit-msg hook already installed at {hook_path}{NC}")
                print(f"{GREEN}Sensitive terms: {', '.join(args.terms)}{NC}")
                return 0
        except Exception:
            # If we can't read, proceed to overwrite.
            pass
    try:
        with open(hook_path, 'w', encoding='utf-8') as f:
            f.write(content)
        os.chmod(hook_path, 0o755)
    except Exception as exc:
        eprint(f"{RED}Error: failed to write hook: {exc}{NC}")
        return 1

    print(f"{GREEN}Installed commit-msg hook at {hook_path}{NC}")
    print(f"{GREEN}Sensitive terms: {', '.join(args.terms)}{NC}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
