"""``git-sensitive-hook`` - install a commit-msg hook that blocks sensitive terms in staged diffs."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from toolscripts.core.log import add_logging_flags, configure_from_args, get_logger

log = get_logger(__name__)

_HOOK_TEMPLATE = '''#!/usr/bin/env python3
# Auto-generated by toolscripts git-sensitive-hook
# Blocks commit when staged changes contain sensitive terms.

from __future__ import annotations

import os
import subprocess
import sys

RED = "\\033[0;31m"
YELLOW = "\\033[0;33m"
NC = "\\033[0m"

SENSITIVE_TERMS = __TERMS__


def _run_git(args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)


def _repo_root() -> str:
    result = _run_git(["git", "rev-parse", "--show-toplevel"])
    return result.stdout.strip() or os.getcwd()


def _scan(terms: list[str]) -> dict[str, set[str]]:
    result = _run_git(["git", "diff", "--cached", "-U0"])
    if result.returncode != 0:
        return {}
    current_file = ""
    hits: dict[str, set[str]] = {}
    lower_terms = [t.lower() for t in terms]
    for line in result.stdout.splitlines():
        if line.startswith("diff --git "):
            parts = line.split(" ")
            if len(parts) >= 4:
                current_file = parts[3].replace("b/", "", 1)
            continue
        if line.startswith("+++ ") or line.startswith("--- ") or line.startswith("@@"):
            continue
        if not line.startswith("+") or line.startswith("+++"):
            continue
        content = line[1:].lower()
        for idx, term in enumerate(lower_terms):
            if term and term in content:
                hits.setdefault(terms[idx], set()).add(current_file or "(unknown)")
    return hits


def main() -> int:
    if not SENSITIVE_TERMS:
        return 0
    os.chdir(_repo_root())
    hits = _scan(SENSITIVE_TERMS)
    if not hits:
        return 0
    sys.stderr.write(f"{RED}Blocked commit: sensitive terms found in staged changes.{NC}\\n")
    for term, files in hits.items():
        sys.stderr.write(f"  - {term} -> {', '.join(sorted(files))}\\n")
    sys.stderr.write(f"{YELLOW}If this is intended, update the hook list.{NC}\\n")
    return 1


if __name__ == "__main__":
    sys.exit(main())
'''


def _resolve_git_dir(cwd: Path) -> Path:
    git_path = cwd / ".git"
    if git_path.is_dir():
        return git_path
    if git_path.is_file():
        first = git_path.read_text(encoding="utf-8").splitlines()[0].strip()
        if not first.startswith("gitdir:"):
            raise RuntimeError(f"unexpected .git file format: {git_path}")
        target = first.split(":", 1)[1].strip()
        target_path = Path(target)
        if not target_path.is_absolute():
            target_path = (cwd / target_path).resolve()
        return target_path
    raise RuntimeError(f".git not found in current directory: {cwd}")


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="git-sensitive-hook",
        description="Install a commit-msg hook that blocks sensitive terms in staged changes.",
    )
    parser.add_argument("terms", nargs="*", help="sensitive terms (space separated)")
    add_logging_flags(parser)
    args = parser.parse_args()
    configure_from_args(args)

    if not args.terms:
        log.error("please provide at least one sensitive term")
        log.warning("example: git-sensitive-hook aaa bbb ccc")
        sys.exit(2)

    try:
        git_dir = _resolve_git_dir(Path.cwd())
    except RuntimeError as exc:
        log.error("%s", exc)
        sys.exit(1)

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / "commit-msg"
    content = _HOOK_TEMPLATE.replace("__TERMS__", repr(list(args.terms)))

    if hook_path.exists():
        try:
            if hook_path.read_text(encoding="utf-8") == content:
                log.success("commit-msg hook already up to date at %s", hook_path)
                log.info("sensitive terms: %s", ", ".join(args.terms))
                return
        except OSError:
            pass

    hook_path.write_text(content, encoding="utf-8")
    os.chmod(hook_path, 0o755)
    log.success("installed commit-msg hook at %s", hook_path)
    log.info("sensitive terms: %s", ", ".join(args.terms))


if __name__ == "__main__":
    main()
